name: Daily Policy Feed Update

on:
  schedule:
    - cron: "0 6 * * *"  # Runs daily at 6:00 UTC
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run updater script
        run: python update_rss.py

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "RSS Bot"
          git config --global user.email "bot@example.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git add feed.xml
          git commit -m "Daily feed update" || echo "No changes to commit"
          git push
