name: Daily Policy Feed Update

on:
  schedule:
    - cron: "0 6 * * *"  # Runs every day at 6:00 UTC
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Run updater script
        run: |
          python update_rss.py

      - name: Commit and push changes
        run: |
          git config --global user.name "RSS Bot"
          git config --global user.email "bot@example.com"
          git add feed.xml
          git commit -m "Daily feed update"
          git push
